name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: "cd-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cd:
    permissions:
      contents: write
      pull-requests: write
    uses: CaptainArbitrary/workflows/.github/workflows/cd.yml@main
